version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: freelancelot
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: freelancelot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://freelancelot:password123@db:5432/freelancelot
    expose:
      - "8000"
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.https.conf:/etc/nginx/conf.d/default.conf  # Use HTTP config first
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - fastapi

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

  certbot-renewer:
    image: certbot/certbot
    container_name: certbot_renewer
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "while :; do
        certbot renew --webroot --webroot-path=/var/www/certbot &&
        nginx -s reload;
        sleep 12h;
      done"
    depends_on:
      - certbot
      - nginx

  telegram-bot:
    build: .
    container_name: telegram_bot
    depends_on:
      - fastapi
      - db
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      BACKEND_LINK_ENDPOINT: http://fastapi:8000/api/link-telegram
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
    command: ["python", "utils/telegram_link_bot.py"]

volumes:
  postgres_data:
